# Generated by Django 3.2.2 on 2021-05-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('job_department', models.CharField(blank=True, max_length=50, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('job_country', models.CharField(blank=True, max_length=50, null=True)),
                ('job_state', models.CharField(blank=True, max_length=50, null=True)),
                ('job_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_employment_type', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Temporary'), (4, 'Contract'), (5, 'Internship'), (6, 'Seasonal'), (7, 'Temporary')], default=1)),
                ('job_category', models.IntegerField(choices=[(1, 'Accounting'), (2, ' Administrative and Clerical'), (3, 'Agriculture'), (4, 'Architectural services'), (5, 'Arts and Entertainment'), (6, 'Automotive'), (7, 'Banking'), (8, 'Biotech, Pharma, R&D'), (9, 'Construction'), (10, 'Consulting'), (11, 'Customer Service, Call Center'), (12, 'Design and Creative'), (13, 'Education and Training'), (14, 'Energy'), (15, 'Engineering'), (16, 'Finance'), (17, 'Government and Nonprofit'), (18, 'Healthcare'), (19, 'Hospitality'), (20, 'Information Technology'), (21, 'Insurance'), (22, 'Internet and Software'), (23, 'Legal'), (24, 'Leisure'), (25, 'Logistics and Transportation'), (26, 'Manufacturing and Production'), (27, 'Marketing and PR'), (28, 'Procurement and Trade'), (29, 'Property'), (30, 'Publishing and Editorial'), (31, 'Recruitment and HR'), (32, 'Retail'), (33, 'Sales'), (34, 'Security and Safety'), (35, 'Science'), (36, 'Technical'), (37, 'Telecommunication'), (38, 'Tourism'), (39, 'Translation Services'), (40, 'Other')], default=1)),
                ('job_required_education', models.IntegerField(choices=[(1, 'High school coursework'), (2, 'High school or equivalent'), (3, 'Certification'), (4, 'Vocational'), (5, 'College coursework completed'), (6, "Associate's degree"), (7, "Bachelor's degree"), (8, "Master's degree"), (9, 'Doctorate'), (10, 'Professional')], default=1)),
                ('job_required_experience', models.IntegerField(choices=[(1, 'Student (High school)'), (2, 'Student(College)'), (3, 'Entry level'), (4, 'Mid level'), (5, 'Experienced'), (6, 'Manager'), (7, 'Senior manager / Supervisor'), (8, 'Executive'), (9, 'Senior executive')], default=1)),
                ('job_lower_hours_per_week', models.IntegerField(default=0)),
                ('job_upper_hours_per_week', models.IntegerField(default=0)),
                ('job_publish_date', models.DateField()),
                ('job_close_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
